#!/usr/bin/env python3
"""Generate the model-set ablation configs m1..m5 from a chosen base config.

The base is the PASLCD variant selected as most promising; re-run this with
a different --base if that choice changes. Each variant is the base with the
listed three_image_comparison keys overridden and nothing else, so a diff of
any two generated files shows exactly the intended change.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]

VARIANTS = {
    # name: (description, overrides)
    "m1_full": ("SAM3 masks + SAM2 + SAM3 features + DINOv2 + geometry", {}),
    "m2_no_dino": ("SAM3 masks + SAM2 + SAM3 features + geometry", {"use_dino_features": False}),
    "m3_no_sam3_features": ("SAM3 masks + SAM2 + DINOv2 + geometry", {"use_sam_features": False}),
    "m4_tracking_geometry": ("SAM3 masks + SAM2 + geometry, no appearance anywhere",
                             {"enable_appearance_correspondence": False,
                              "use_sam_features": False, "use_dino_features": False}),
    "m5_features_geometry_no_sam2": ("SAM3 masks + DINOv2 + SAM3 features + geometry, no SAM2",
                                     {"enable_tracking": False}),
}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--base", type=Path, required=True)
    ap.add_argument("--out-dir", type=Path, default=REPO / "configs")
    args = ap.parse_args()

    base_text = args.base.read_text()
    base = yaml.safe_load(base_text)
    for name, (description, overrides) in VARIANTS.items():
        cfg = yaml.safe_load(base_text)
        cfg["three_image_comparison"].update(overrides)
        out = args.out_dir / f"model_ablation_{name}.yaml"
        header = (f"# Model-set ablation variant {name}: {description}\n"
                  f"# Generated by scripts/make_model_ablation_configs.py from {args.base.name};\n"
                  f"# three_image_comparison overrides: {overrides or 'none (base as-is)'}\n")
        out.write_text(header + yaml.safe_dump(cfg, sort_keys=False))
        print(f"wrote {out}  overrides={overrides}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
